---
# tasks file for docker-compose_restart

- name: Pull existing repository
  shell:
   cd ~/Devs-Unleashed-Hackathon-backend && git pull -p
  register: pull_results


- name: Remove old .env files
  shell:
   cd ~/Devs-Unleashed-Hackathon-backend && rm .env && rm .env-db


- name: Set new .env files
  copy:
   src: "{{ item }}"
   dest: "{{ destination }}"
   mode: 0664
  loop:
   - ".env"
   - ".env-db" 
  register: copy_results


- name: Restart Docker Compose
  shell:
   cd ~/Devs-Unleashed-Hackathon-backend  && docker-compose up -d --build
  register: docker_compose_results


- name: Show pull output
  debug:
   var: pull_results


- name: Show copy results
  debug:
   var: copy_results


- name: Show Docker Compose restart output
  debug:
   var: docker_compose_results

