name: Restart Docker Compose
on:
  push:
    branches: 
      - main

jobs:
  docker_compose_restart:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
        with:
          ref: main
          
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.1
          
      - name: Setup envs
        env:
          ANSIBLE_SSH_PRIVATE_KEY : ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
          ANSIBLE_INVENTORY: ${{ secrets.ANSIBLE_INVENTORY }}
          ENV : ${{ secrets.ENV }}
          ENV_DB: ${{ secrets.ENV_DB }}
          
        run: |
          echo "$ANSIBLE_SSH_PRIVATE_KEY" > ansible/frank-hackaton.pem
          echo "$ANSIBLE_INVENTORY" > ansible/hosts.txt
          chmod 600 ansible/frank-hackaton.pem
          echo "$ENV" > ansible/roles/compose_restart/files/.env
          echo "$ENV_DB" > ansible/roles/compose_restart/files/.env-db
          
      - name: Install ansible
        run: |
          python -m pip install --upgrade pip && python -m pip install --user ansible

      - name: Run Ansible playbook
        run: cd ansible/ && ansible-playbook -i hosts.txt compose_restart-role.yml


